name: Upload to App Store Connect

on:
  push:
    branches:
      - master

jobs:
  upload_to_app_store_connect:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'Update versions')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up API keys
      run: |
        echo "API_KEY_YANDEX_METRICA=${{ secrets.API_KEY_YANDEX_METRICA }}" >> $GITHUB_ENV
        echo "API_KEY_APPHUD=${{ secrets.API_KEY_APPHUD }}" >> $GITHUB_ENV
        echo "API_KEY_KINOPOISK=${{ secrets.API_KEY_KINOPOISK }}" >> $GITHUB_ENV
        echo "API_KEY_MOST_POPULAR_MOVIES=${{ secrets.API_KEY_MOST_POPULAR_MOVIES }}" >> $GITHUB_ENV
        echo "FANCY_BACKEND=${{ secrets.FANCY_BACKEND }}" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Set up Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Set up Tuist
      run: |
        curl -Ls https://install.tuist.io | bash

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Set up fastlane
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    
    - name: Run fastlane match
      run: |
        bundle exec fastlane match appstore
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

    - name: Tuist fetch
      run: |
        tuist fetch

    - name: Download App versions from SosinVitalii.com server
      run: |
        curl --ssl-reqd --insecure --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} -O "ftp://${{ secrets.FTP_SERVER }}/avatars_versions.json"

    - name: Increase App version and build number
      run: |
        python Scripts/update_version_and_build_number.py

    - name: Update marketing and current project version in Project
      run: |
        python Scripts/update_appearance_versions.py

    - name: Upload App versions to SosinVitalii.com server
      run: |
        curl --ssl-reqd --insecure --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} -T "./avatars_versions.json" "ftp://${{ secrets.FTP_SERVER }}/avatars_versions.json"

    - name: Tuist generate
      run: |
        tuist generate

    - name: Build and archive the app
      run: |
        bundle exec fastlane build
      env:
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    - name: Upload App build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Avatars
        path: "Avatars.ipa"

    - name: Upload dSYM build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Avatars.app.dSYM
        path: "Avatars.app.dSYM.zip"

    - name: Upload to App Store Connect
      run: |
        bundle exec fastlane upload_app_to_app_store
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        PROVISIONING_PROFILE_UUID: ${{ env.PROVISIONING_PROFILE_UUID }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
        APP_STORE_CONNECT_TEAM_NAME: ${{ secrets.APP_STORE_CONNECT_TEAM_NAME }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

    - name: Clean up App Store Connect API key
      run: |
        rm -f /tmp/AuthKey.p8

    - name: Get MARKETING_VERSION and CURRENT_PROJECT_VERSION
      run: |
        echo "MARKETING_VERSION=$(jq -r '.marketing_version' avatars_versions.json)" >> $GITHUB_ENV
        echo "CURRENT_PROJECT_VERSION=$(jq -r '.current_project_version' avatars_versions.json)" >> $GITHUB_ENV

    - name: Create and push Release git tag
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git checkout ${GITHUB_HEAD_REF}
        git tag "${{ env.MARKETING_VERSION }}"
        git push --tags
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: Send Telegram notification "New Release"
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python Scripts/send_telegram.py "üòç Release iOS Avatars AI ${{ env.MARKETING_VERSION }} üòç
        –ê–≤—Ç–æ—Ä: ${{ github.actor }}
        –°–±–æ—Ä–∫–∞ ‚Ññ: ${{ env.MARKETING_VERSION }}/${{ env.CURRENT_PROJECT_VERSION }}
        
        –î–ª—è —Ç–µ—Å—Ç–∏—Ä–æ–≤–∞–Ω–∏—è —Ä–µ–ª–∏–∑–Ω—ã—Ö —Å–±–æ—Ä–æ–∫ –æ—Ç–ø—Ä–∞–≤—å—Ç–µ —Å–≤–æ–π Apple ID (example@iCloud.com) –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é @V1taS
        "
